apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi # should be less than or equal to your disk size
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0c37b65c7b5cc5e5c

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs # this is the pv name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi