apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi # should be less than or equal to your disk size
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0b131548c5ae8607a

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static # this is the pv name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: html-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  volumes:
  - name: html-data
    persistentVolumeClaim:
      claimName: ebs-static