kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: roboshop-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-04ddb450147077faa
  directoryPerms: "700"
  basepath: "/roboshop"
  reclaimPolicy: Retain