apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    componsnt:  frontend
    environment: dev
  annotations:
    imageregistry: "https://hub.docker.com/"
    jenkinsurl: "http://jenkins.vinoddevops.com/build/jobs/roboshop/34"
    
spec:
  containers:
  - name: nginx
    image: nginx