apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
       #soft limit
      requests:
        memory: "64Mi"  
        cpu: "100m"    #cpu
        #hard limit
      limits:
        memory: "128Mi"
        cpu: "150m"    #cpu