apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # these lables are replica set lables
  labels:
    project: roboshop
    purpose: rs-demo
    tier: frontend
spec:
  replicas: 10
  selector:
  # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      purpose: rs-demo
      tier: frontend
# This is pod definition. pod is subset of replica set
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine3.23-perl